#!/usr/bin/env bash
# installs and sets up nginx on a computer/server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo apt-get -y install nginx-extras
sudo chown -R "$USER:$USER" /var/www/html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
