#!/usr/bin/env bash
# installs and sets up nginx on a computer/server

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER:$USER" /var/www/html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo nginx -s reload
