#!/usr/bin/env bash
# Configure an Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo apt-get -y install nginx-extras
sudo chmod '666' /var/www/html/index.nginx-debian.html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i '/# pass PHP scripts to FastCGI server/i \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-enabled/default
sudo touch /var/www/html/custom_404.html
sudo chmod '666' /var/www/html/custom_404.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i '/# pass PHP scripts to FastCGI server/i \\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n' /etc/nginx/sites-enabled/default
sudo sed -i "/try_files \$uri \$uri\/ =404;/a \\\t\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo service nginx restart
