#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

pgrep -f "$(basename "$0")" >> /var/run/myscript.pid

function quit ()
{
	rm /var/run/myscript.pid
	exit 0
}

function trap_sigterm ()
{
	echo "I hate the kill command"
	quit
}

trap trap_sigterm SIGTERM
trap quit SIGQUIT
trap "echo Y U no love me?!" SIGINT

while ((1)); do
	echo "To infinity and beyond"
	sleep 2
done
