#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

num=1
while ((num <= 10)); do
	echo "Best School"
	if ((num == 9))
	then
		echo "Hi"
	fi
	num=$((num += 1))
done
